### ISSUE TITLE
Won't run?

### ISSUE THREAD

**Issue by bigdork** [vladimir-tutin/Plex-Auto-Collections#11]
Really excited about this, and hope I can get it working. 

I've added my servers and tokens/keys to the template file but left the rest as-provided for a trial run. My Plex and Radarr servers are behind a reverse proxy, so I configured as:
```
plex:
  library: Movies
  token: ###################
  url: https://plex.domain.tld
radarr:
  url: https://radarr.domain.tld/radarr/
  token: ###########################
  quality_profile_id: 4
  search: true
```

Unfortunately, I get no love when running the script. :(
```
$ sudo python plex_auto_collections.py --noserver
Traceback (most recent call last):
  File "plex_auto_collections.py", line 5, in <module>
    from plexapi.video import Movie
  File "/usr/local/lib/python2.7/dist-packages/plexapi/__init__.py", line 6, in <module>
    from plexapi.config import PlexConfig, reset_base_headers
  File "/usr/local/lib/python2.7/dist-packages/plexapi/config.py", line 4, in <module>
    from plexapi.compat import ConfigParser
  File "/usr/local/lib/python2.7/dist-packages/plexapi/compat.py", line 50, in <module>
    from mock import patch, MagicMock
ImportError: No module named mock
```

**Comment by zb140** [comment]
super late to the party, but in case you (or someone else reading this) are still looking for an answer, it's because the default `python` on your system is version 2.7.  Running it with `python3` will work.
