### ISSUE TITLE
Error when adding to Radarr because of the year?

### ISSUE THREAD

**Issue by ShadowFM** [vladimir-tutin/Plex-Auto-Collections#12]
If I want to add the missing movies to radarr I got this error, seems because of the 
tmdb_year?

I'm using tmdb and imdb lists.

```
Add missing movies to Radarr? (y/n): y
 INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.themoviedb.org
Traceback (most recent call last):
   File "plex_auto_collections.py", line 163, in <module>
     update_from_config(plex)
   File "/home/Plex-Auto-Collections/config_tools.py", line 99, in update_from_config
     add_to_radarr(missing)
   File "/home/Plex-Auto-Collections/radarr_tools.py", line 42, in add_to_radarr
     "year": int(tmdb_year),
 ValueError: invalid literal for int() with base 10: ''
```

**Comment by burkasaurusrex** [comment]
A lot of TMDb collections will have movies that will be released in the future without an exact date. Radarr's API generally needs a year in order to properly add a movie. So when there's not a year, it will cause the script to stop processing others in the list. This error is fixed in [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections). That fork also includes some additional features and fixes.
