### ISSUE TITLE
Error Adding Not Existing to Radarr..

### ISSUE THREAD

**Issue by MiX74P3** [vladimir-tutin/Plex-Auto-Collections#13]
Select Mode: l
Enter list type IMDB(i) TMDb(t): i
Enter IMDB List URL: https://www.imdb.com/list/ls068935239/
Enter collection name: Spider Man Film Series
Processing IMDB List: https://www.imdb.com/list/ls068935239/
+++ Adding Spider-Man to collection: Spider Man Film Series
+++ Adding Spider-Man 2 to collection: Spider Man Film Series
+++ Adding Spider-Man 3 to collection: Spider Man Film Series
+++ Adding The Amazing Spider-Man to collection: Spider Man Film Series
+++ Adding The Amazing Spider-Man 2 to collection: Spider Man Film Series
+++ Adding Spider-Man: Homecoming to collection: Spider Man Film Series
+++ Adding Spider-Man: Into the Spider-Verse to collection: Spider Man Film Series
+++ Adding Spider-Man: Far from Home to collection: Spider Man Film Series
8 missing movies from IMDB List: https://www.imdb.com/list/ls068935239/
Add missing movies to Radarr? (y/n)y
Traceback (most recent call last):
  File "plex_auto_collections.py", line 200, in <module>
    add_to_radarr(missing)
  File "\Plex-Auto-Collections-master\radarr_tools.py", line 27, in add_to_radarr
    tmdb_details = movie.external(external_id=str(m), external_source="imdb_id")['movie_results'][0]
IndexError: list index out of range

Can anyone help me figure out why this doesnt seem to be connecting to radarr?

**Comment by burkasaurusrex** [comment]
It looks like the first entry in the list is a TV show? This will case the script to stop processing others in the list. This error is fixed in [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections). That fork also includes some additional features and fixes.
