### ISSUE TITLE
i can't do it to run

### ISSUE THREAD

**Issue by jalarab** [vladimir-tutin/Plex-Auto-Collections#18]
F:\rclone\Plex-Auto-Collections-master>python3 plex_auto_collections.py
==================================================================
 Plex Auto Collections by /u/iRawrz
==================================================================
Attempting to start image server
IMAGE SERVER NOT RUNNING
Update Collections from Config? (y/n): n

Modes: Rescan (r), Actor(a), IMDB/TMDb List(l), Add to Existing Collection (+), Delete(-), Search(s), Quit(q)

Select Mode: l
Enter list type IMDB(i) TMDb(t): i
Enter IMDB List URL: https://www.imdb.com/list/ls043839435
Enter collection name: BEST
Processing IMDB List: https://www.imdb.com/list/ls043839435
Traceback (most recent call last):
  File "plex_auto_collections.py", line 196, in <module>
    missing = plex_tools.add_to_collection(plex, method, url, c_name)
  File "F:\rclone\Plex-Auto-Collections-master\plex_tools.py", line 97, in add_to_collection
    movies, missing = imdb_tools.imdb_get_movies(plex, value)
  File "F:\rclone\Plex-Auto-Collections-master\imdb_tools.py", line 33, in imdb_get_movies
    imdb_id = tmdbapi.imdb_id
AttributeError: 'AsObj' object has no attribute 'imdb_id'

**Comment by meisnate12** [comment]
I know this is late but this issue has been fixed in the fork [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections) as well as many other improvements and bug fixes
