### ISSUE TITLE
KeyError: 'image-server'

### ISSUE THREAD

**Issue by Septan** [vladimir-tutin/Plex-Auto-Collections#2]
Using python 3.7.4 and using noserver command and without.

````
Traceback (most recent call last):
  File "plex_auto_collections.py", line 135, in <module>
    plex = Plex()
  File "C:\Scripts\Plex-Auto-Collections\config_tools.py", line 28, in __init__
    config = Config().plex
  File "C:\Scripts\Plex-Auto-Collections\config_tools.py", line 23, in __init__
    self.image_server = self.data['image-server']
KeyError: 'image-server'
````

**Comment by vladimir-tutin** [comment]
Looks like I forgot to update the main config.yml.template with the image_server key. I've updated the config.yml.template with the section that's missing. I've added that section in and will push an update later to not require that section if it isn't wanted.
