### ISSUE TITLE
Fails to import, even with default configs (adjusted for keys and whatnot)

### ISSUE THREAD

**Issue by twhiting9275** [vladimir-tutin/Plex-Auto-Collections#21]
So, this appears to be broken. Not sure when it broke, but something is missing somewhere. Perhaps tmdb updated something on their end? 

Checked the collection URL, it's still there
Everything starts up fine
Config:
```
collections:
  Jurassic Park:
    tmdb-list: https://www.themoviedb.org/collection/328
    details:
      tmdb-summary: 328
      poster: https://i.imgur.com/QMjbyCX.png
  1080p Documentaries:
    genres: Documentary
    subfilters:
      video-resolution: 1080
    details:
      summary: A collection of 1080p Documentaries
  Dave Chappelle:
    actors: Dave Chappelle
    details:
      tmdb-summary: 4169
plex:
  library: Movies
  token: mykey
  url: http://localhost:32400
radarr:
  url: http://localhost:7878/radarr/
  token: mykey
  quality_profile_id: 4
  search: true
tmdb:
  apikey: mykey
  language: en
image-server:
  host: 0.0.0.0
  port: 5000
```

Error:
```
Updating collection: Jurassic Park...
Processing tmdb-list: https://www.themoviedb.org/collection/328
Traceback (most recent call last):
  File "D:\Plex Auto Collections\plex_auto_collections.py", line 159, in <module>
    update_from_config(plex, True)
  File "D:\Plex Auto Collections\config_tools.py", line 85, in update_from_config
    missing = add_to_collection(plex, m, v, c, subfilters)
  File "D:\Plex Auto Collections\plex_tools.py", line 99, in add_to_collection
    movies, missing = imdb_tools.tmdb_get_movies(plex, value)
  File "D:\Plex Auto Collections\imdb_tools.py", line 103, in tmdb_get_movies
    imdb_id = t_movie.details(mid).entries['imdb_id']
AttributeError: 'AsObj' object has no attribute 'entries'
```

**Comment by burkasaurusrex** [comment]
I'd recommend checking out this fork instead: [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections)

**Comment by twhiting9275** [comment]
> I'd recommend checking out this fork instead: [mza921/Plex-Auto-Collections](https://github.com/mza921/Plex-Auto-Collections)

Thank you, that did it. Had to tweak the config file a bit, but no problem once it was done.
Again, thank you :)
