### ISSUE TITLE
Error when adding to Radarr

### ISSUE THREAD

**Issue by Septan** [vladimir-tutin/Plex-Auto-Collections#3]
I get same error when pressing y and n
````
Add missing movies to Radarr? (y/n): n
Traceback (most recent call last):
  File "plex_auto_collections.py", line 163, in <module>
    update_from_config(plex)
  File "C:\Scripts\Plex-Auto-Collections\config_tools.py", line 147, in update_from_config
    if not r.status_code == 404:
UnboundLocalError: local variable 'r' referenced before assignment
````

**Comment by vladimir-tutin** [comment]
Bug was actually with the image server. It should be resolved now. I was able to reproduce it by putting in invalid settings for the image server, so if you're trying to use that check the IP address in the configuration and make sure it matches your machine.
