### ISSUE TITLE
Radarr - Unable to add missing movie

### ISSUE THREAD

**Issue by bsquidwrd** [vladimir-tutin/Plex-Auto-Collections#5]
* Do you want to add the missing movie(s) to Radarr?: Y

```
Traceback (most recent call last):
  File ".\plex_auto_collections.py", line 163, in <module>
    update_from_config(plex)
  File "E:\Desktop\plex_auto_collections\src\config_tools.py", line 99, in update_from_config
    add_to_radarr(missing)
  File "E:\Desktop\plex_auto_collections\src\radarr_tools.py", line 63, in add_to_radarr
    r_json = json.loads(response.text)
  File "c:\program files (x86)\python37-32\Lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\program files (x86)\python37-32\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\program files (x86)\python37-32\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The returned JSON isn't actually JSON, it's HTML. It's the Login page when using Form login for Radarr despite other programs working just fine with the API. When I disable Form login and leave Authentication as "None" everything works fine (or at least how I assume you intended it to). I get a JSON result of "Method not allowed" but the script reports back "Movie added"

```html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Radarr - Login</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- Windows Phone -->
    <meta name="msapplication-navbutton-color" content="#272727">

    <link href="/Content/bootstrap.css?h=Cu08P6VKGmbL7JR+REz7Nw" rel="stylesheet" type="text/css">
    <link href="/Content/theme.css?h=r+l+XCXGunbkiZN2kuW3jw" rel="stylesheet" type="text/css">

    <!-- Generated by http://realfavicongenerator.net/ -->
    <link rel="apple-touch-icon" sizes="180x180" href="/Content/Images/favicon/apple-touch-icon.png?h=wqn3LPqe9L7Mdy8YOjIqYg">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-32x32.png?h=ZJ4JfONLrN5b2Y6sEqBo7A" sizes="32x32">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-194x194.png?h=EeRVsUsk7ufo1yG0XU2Ecg" sizes="194x194">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/android-chrome-192x192.png?h=UWXDD5pf6z2s53VvdyPifg" sizes="192x192">
    <link rel="icon" type="image/png" href="/Content/Images/favicon/favicon-16x16.png?h=Rx3sPCyp5ur5tyAOlsDZ8Q" sizes="16x16">
    <link rel="manifest" href="/Content/Images/favicon/manifest.json?h=UOC2tVUccFD1uRu+tYVO/g">
    <link rel="mask-icon" href="/Content/Images/favicon/safari-pinned-tab.svg?h=mBKYFJ+Iy7on6F1XwRRN9Q" color="#ffc230">
    <link rel="shortcut icon" href="/Content/Images/favicon/favicon.ico?h=5rhS3DvgQdQTAys3GmDWXw">
    <meta name="apple-mobile-web-app-title" content="Radarr">
    <meta name="application-name" content="Radarr">
    <meta name="msapplication-TileColor" content="#272727">
    <meta name="msapplication-TileImage" content="/Content/Images/favicon/mstile-144x144.png">
    <meta name="msapplication-config" content="/Content/Images/favicon/browserconfig.xml">
    <meta name="theme-color" content="#272727">
</head>
<body>
<div class="container">
    <div id="nav-region"></div>
</div>
<div id="page">
    <div class="page-container">
        <div class="container-fluid">
            <div class="container-fluid main-region" id="main-region">
                <div class="col-md-2 col-md-offset-5">
                    <form name="login" id="login" class="login" method="POST">
                        <h2><img src="/Content/Images/logos/32.png?h=m90WXSMGB/SFsmOfx8768Q" alt=""/> Radarr</h2>
                        <div class="form-group">
                            <label for="username" class="sr-only">Email address</label>
                            <input type="text" id="username" name="username" class="form-control" placeholder="Username" required autofocus>
                        </div>

                        <div class="form-group">
                            <label for="password" class="sr-only">Password</label>
                            <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
                        </div>

                        <div class="checkbox">
                            <label>
                                <input type="checkbox" name="rememberMe" checked="checked"> Remember me
                            </label>
                        </div>

                        <input class="btn btn-lg btn-primary btn-block" type="submit" value="Log in" />
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
```

**Comment by bsquidwrd** [comment]
Found my issue. The template puts `/radarr/` as a url suffix but I access Radarr via `http://host:port/`. I had to remove the `/radarr/` suffix from my URL for it to work. Maybe this could be something added as a Radarr config variable? Something like `URL_Base` (since that's what it is called in Radarr settings)
