### ISSUE TITLE
TypeError: 'encoding' is an invalid keyword argument for this function`

### ISSUE THREAD

**Issue by scrathe** [vladimir-tutin/Plex-Auto-Collections#6]
Ran into this error when running this on a Linux VM (Linux Mint 19.1, Python 2.7.15)

```Traceback (most recent call last):
  File "plex_auto_collections.py", line 135, in <module>
    plex = Plex()
  File "/home/loki/Plex-Auto-Collections/config_tools.py", line 28, in __init__
    config = Config().plex
  File "/home/loki/Plex-Auto-Collections/config_tools.py", line 17, in __init__
    with open(self.config_path, 'rt', encoding='utf-8') as yml:
TypeError: 'encoding' is an invalid keyword argument for this function
```

Fixed this issue by adding this to config_tools.py
`from io import open`

**Comment by scrathe** [comment]
Problem fixed when using Python3
