### ISSUE TITLE
Error when adding to Radarr

### ISSUE THREAD

**Issue by scrathe** [vladimir-tutin/Plex-Auto-Collections#7]
```
Add missing movies to Radarr? (y/n)y
Traceback (most recent call last):
  File "plex_auto_collections.py", line 200, in <module>
    add_to_radarr(missing)
  File "/home/loki/Plex-Auto-Collections/radarr_tools.py", line 62, in add_to_radarr
    r_json = json.loads(response.text)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by scrathe** [comment]
Duplicate of issue #5. config.yml had ip:7878/radarr. Removed /radarr and it started working.
